language: php

php: [5.5, 5.4]

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update
  - composer install
  - composer global require drush/drush:dev-master --prefer-source

before_script:
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Setup a stack Drupal 6 install to test api abilities.
  - mysql -e 'create database drupal6'
  - drush --quiet dl drupal-6 --drupal-project-rename=drupal6
  - drush --yes --root=$PWD/drupal6 site-install --db-url=mysql://travis:@127.0.0.1/drupal6
  - cp -r fixtures/drupal6/modules/behat_test drupal6/sites/all/modules
  - cd drupal6
  - drush --yes en behat_test
#  - drush --yes fr behat_test
  - drush cc all
  - drush --debug runserver :8886 > ~/debug6.txt 2>&1 &
  - cd -
  # Setup a stock Drupal 7 install to test api abilities.
  - mysql -e 'create database drupal7'
  - drush --quiet dl drupal-7 --drupal-project-rename=drupal7
  - drush --yes --root=$PWD/drupal7 site-install --db-url=mysql://travis:@127.0.0.1/drupal7
  - cp -r fixtures/drupal7/modules/behat_test drupal7/sites/all/modules
  - cd drupal7
  - drush --yes en behat_test
  - drush --yes fr behat_test
  - drush cc all
  - drush --debug runserver :8887 > ~/debug7.txt 2>&1 &
  - cd -
  # Setup a stock Drupal 8 install to test api abilities.
  - mysql -e 'create database drupal8'
  - (cd drupal8 && git pull && cd -) || git clone --branch 8.0.x http://git.drupal.org/project/drupal.git drupal8
  - drush --yes --root=$PWD/drupal8 site-install --db-url=mysql://travis:@127.0.0.1/drupal8
  - cp -r fixtures/drupal8/modules/behat_test drupal8/modules
  - cd drupal8
  - drush --yes en behat_test
  - drush --yes pmu page_cache
  - drush cr
  - drush runserver :8888 > ~/debug8.txt 2>&1 &
  - cd -
  - sleep 4s

script:
  - vendor/bin/phpspec run -f pretty --no-interaction
  - vendor/bin/behat -fprogress --strict
  - vendor/bin/behat -fprogress --profile=drupal6 --strict
  - vendor/bin/behat -fprogress --profile=drupal7 --strict
  - vendor/bin/behat -fprogress --profile=drush --strict
  - vendor/bin/behat -fprogress --profile=drupal8 --strict

after_failure:
  - cat ~/debug6.txt
  - cat ~/debug7.txt
  - cat ~/debug8.txt
