language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - PATH=$PATH:/home/travis/.config/composer/vendor/bin
    - TRAVIS_NODE_VERSION="4.0.0"
  matrix:
    - DRUPAL_VERSION=7
    - DRUPAL_VERSION=8

# Enable Travis containers.
sudo: false

services:
  - mysql

install:
  - composer self-update
  # For Drupal 8 install the behat drush endpoint.
  # Pins symfony/dependency-injection to match core.
  # @see https://github.com/jhedstrom/drupalextension/issues/413
  # @todo Re-enable behat drush endpoint testing.
  # @see https://github.com/jhedstrom/drupalextension/issues/458
  - test ${DRUPAL_VERSION} -ne 8 || COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require drush/drush:~10.0 symfony/dependency-injection:3.4.4
  - composer install
  # For Drupal 8, change composer.json to require symfony 3.x as conflicting
  # versions between the separate drupal and drupalextension vendor folders
  # can create conflicts.
  # @todo Change test process to require drupalextension from the local folder
  #   to let composer handle compatibility and simulate a more common process.
  - test ${DRUPAL_VERSION} -ne 8 || COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require "symfony/browser-kit:~3.4" "symfony/dependency-injection:~3.0" "symfony/translation:^3.4"
  # Install drush globally.
  - (test ${DRUPAL_VERSION} -ne 8 && composer global require drush/drush:~8.0 drupal/drupal-driver) || composer global require drush/drush:~10.0
  # Install the Behat Drush Endpoint for Drupal 7 tests.
  - test ${DRUPAL_VERSION} -ne 7 || (git clone https://github.com/drush-ops/behat-drush-endpoint.git drush/behat-drush-endpoint && (cd drush/behat-drush-endpoint && composer install && cd -))
  # Pin node version.
  # @see http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  # Define the module path according to the Drupal version being tested.
  - test ${DRUPAL_VERSION} -ne 8 || export MODULE_PATH="drupal/modules"
  - test ${DRUPAL_VERSION} -eq 8 || export MODULE_PATH="drupal/sites/all/modules" && mkdir -p ${MODULE_PATH}
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - mysql -e 'create database drupal'
  # Download and install Drupal so we can test API abilities.
  # For Drush 9, dl is deprecated so we must use composer. However, we still
  # cannot simply require drupal/drupal since it hardcodes it's autoloader
  # and we'd need to use drupal-scaffold, etc, etc.
  - test ${DRUPAL_VERSION} -eq 8 || drush dl --quiet --yes drupal-${DRUPAL_VERSION}.x --all --drupal-project-rename=drupal
  - test ${DRUPAL_VERSION} -ne 8 || (mkdir -p tmp && cd tmp && composer require --no-interaction drupal/drupal && cd - && rm -rf drupal && mv tmp/vendor/drupal/drupal ./drupal && cd drupal && composer install && cd - && rm -rf tmp)
  - drush --yes --root=$PWD/drupal site-install --db-url=mysql://travis:@127.0.0.1/drupal
  # Copy the static HTML that is used for blackbox testing in the web root.
  - cp -r fixtures/blackbox $PWD/drupal
  # Copy our test module to the correct location.
  - cp -r fixtures/drupal${DRUPAL_VERSION}/modules/behat_test ${MODULE_PATH}
  - cd drupal
  - drush --yes en behat_test
  - drush cc drush
  # @todo Re-enable behat drush endpoint testing.
  # @see https://github.com/jhedstrom/drupalextension/issues/458
  # - test ${DRUPAL_VERSION} -eq 6 || test ${DRUPAL_VERSION} -eq 8 || (test ${DRUPAL_VERSION} -eq 7 && drush help behat)
  # Only revert features on Drupal 7.
  - test \! ${DRUPAL_VERSION} -eq 7 || drush --yes fr behat_test
  # Disable the page cache on Drupal 8.
  - test \! ${DRUPAL_VERSION} -eq 8 || drush --yes pmu page_cache
  # Test with big_pipe enabled for Drupal 8.
  - test \! ${DRUPAL_VERSION} -eq 8 || drush --yes en -y big_pipe
  # Clear the cache on Drupal 6 and 7, rebuild on Drupal 8.
  - test ${DRUPAL_VERSION} -eq 8 && drush cr || drush cc all || true
  - drush --debug runserver :8888 > ~/debug.txt 2>&1 &
  - cd -
  - sleep 4s

script:
  - composer test
  - npm test
  - vendor/bin/behat -fprogress --strict
  - vendor/bin/behat -fprogress --profile=drupal${DRUPAL_VERSION} --strict
  # Do not test the Drush profile unless Drupal 7 was installed.
  - test ${DRUPAL_VERSION} -ne 7 || vendor/bin/behat -fprogress --profile=drush --strict

after_failure:
  - cat ~/debug.txt
