parameters:
  # This overrides the class for the core version of this class
  behat.definition.proposal.annotated.class: Drupal\DrupalExtension\Definition\Proposal\AnnotatedDefinitionProposal

  # Drupal driver manager.
  drupal.drupal.class: Drupal\Drupal
  drupal.drupal.default_session: blackbox
  drupal.drupal.api_driver: drush

  # Random generator.
  drupal.random.class: Drupal\Component\Utility\Random

  # Context initializer.
  drupal.context.initializer.class: Drupal\DrupalExtension\Context\Initializer\DrupalAwareInitializer

  # Context class guesser.
  drupal.context.class_guesser.class: Drupal\DrupalExtension\Context\ClassGuesser\DrupalContextClassGuesser

  # Event dispatcher.
  drupal.event_dispatcher.class: Symfony\Component\EventDispatcher\EventDispatcher

  # Hook dispatcher.
  drupal.hook.dispatcher.class: Drupal\DrupalExtension\Hook\Dispatcher

  # Hook loader.
  drupal.context.loader.annotated.class: Drupal\DrupalExtension\Context\Loader\Annotated

  # Region selector class.
  drupal.context.region_selector.class: Drupal\DrupalExtension\Selector\RegionSelector

  # Parameters.
  drupal.basic_auth: { username: ~, password: ~}
  drupal.parameters: {}
  drupal.region_map: {}

services:
  drupal.drupal:
    class: %drupal.drupal.class%
    arguments:
      - {}
      - @drupal.random
  drupal.random:
    class: %drupal.random.class%
  drupal.context.initializer:
    class: %drupal.context.initializer.class%
    arguments:
      - @drupal.drupal
      - %drupal.parameters%
      - @drupal.event_dispatcher
    tags:
      - { name: context.initializer }
      - { name: event_dispatcher.subscriber, priority: 0 }
  drupal.context.class_guesser:
    class: %drupal.context.class_guesser.class%
    tags:
      - { name: behat.context.class_guesser }
  drupal.event_dispatcher:
    class: %drupal.event_dispatcher.class%
  drupal.hook.dispatcher:
    class: %drupal.hook.dispatcher.class%
    tags:
      - { name: drupal.event_subscriber }
  drupal.context.loader.annotated:
    class: %drupal.context.loader.annotated.class%
    arguments:
      - @drupal.hook.dispatcher
    tags:
      - { name: behat.context.loader }
  drupal.region_selector:
    class: %drupal.context.region_selector.class%
    arguments:
      # inject the CSSSelector
      - "@mink.selector.css"
      - %drupal.region_map%
    tags:
      - { name: mink.selector, alias: region }
