parameters:
  drupal.driver.drupal.class: Drupal\Driver\DrupalDriver

  # Core controllers.
  drupal.driver.cores.7.class: Drupal\Driver\Cores\Drupal7
  drupal.driver.cores.8.class: Drupal\Driver\Cores\Drupal8

services:
  drupal.driver.drupal:
    class: %drupal.driver.drupal.class%
    arguments:
      - %drupal.driver.drupal.drupal_root%
      - %mink.base_url%
      - @drupal.random
    tags:
      - { name: drupal.driver, alias: drupal }
  drupal.driver.cores.7:
    class: %drupal.driver.cores.7.class%
    tags:
      - { name: drupal.core, alias: 7 }
    arguments:
      - %drupal.driver.drupal.drupal_root%
      - %mink.base_url%
      - @drupal.random
  drupal.driver.cores.8:
    class: %drupal.driver.cores.8.class%
    tags:
      - { name: drupal.core, alias: 8 }
    arguments:
      - %drupal.driver.drupal.drupal_root%
      - %mink.base_url%
      - @drupal.random
